/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

// Read Vite env vars at build-time. Vite exposes `import.meta.env`; during
// SSR or other runtimes `import.meta` may not exist, so fall back to the
// hard-coded defaults below. Access `import.meta.env` inside a try/catch to
// avoid using invalid expressions like `import as any` which break TypeScript
// parsing in some environments.
let _env: any;
if (typeof window !== 'undefined' && (window as any).__import_meta_fallback__?.env) {
  _env = (window as any).__import_meta_fallback__.env;
} else {
  try {
    // Access `import.meta` via a dynamic Function to avoid parse-time
    // issues in TypeScript/TSX parsers that can misinterpret `as` assertions.
    // This evaluates at runtime only when supported.
    // eslint-disable-next-line no-new-func
    const getImportMetaEnv = new Function('return (typeof import !== "undefined" && import.meta && import.meta.env) ? import.meta.env : undefined');
    _env = getImportMetaEnv();
  } catch (e) {
    _env = undefined;
  }
}

export const projectId = (_env && _env.VITE_SUPABASE_PROJECT_ID) ? _env.VITE_SUPABASE_PROJECT_ID : "bnjiemwngpbweiphjyvv";

export const publicAnonKey = (_env && _env.VITE_SUPABASE_ANON_KEY)
  ? _env.VITE_SUPABASE_ANON_KEY
  : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJuamllbXduZ3Bid2VpcGhqeXZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ1OTUyOTMsImV4cCI6MjA4MDE3MTI5M30.mOPw6dxM2T_NbgHNCWWasNnq_BbLwNsyeoN_cOecEUE";