/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Table schema:
CREATE TABLE kv_store_f258bbc4 (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

// View at https://supabase.com/dashboard/project/bnjiemwngpbweiphjyvv/database/tables

// This file provides a simple key-value interface for storing Figma Make data. It should be adequate for most small-scale use cases.
// Server-side kv_store moved to /server to avoid bundling in client build.
// Keep this stub in `src` to avoid import errors if accidentally imported in client code.
export const set = async () => { throw new Error('kv_store is server-only; use server functions instead'); };
export const get = async () => { throw new Error('kv_store is server-only; use server functions instead'); };
export const del = async () => { throw new Error('kv_store is server-only; use server functions instead'); };
export const mset = async () => { throw new Error('kv_store is server-only; use server functions instead'); };
export const mget = async () => { throw new Error('kv_store is server-only; use server functions instead'); };
export const mdel = async () => { throw new Error('kv_store is server-only; use server functions instead'); };
export const getByPrefix = async () => { throw new Error('kv_store is server-only; use server functions instead'); };